# Configurações padrão para todos os ambientes.
# O Rails usa esta seção para herdar configurações comuns.
default: &default
  adapter: postgresql # Mude para postgresql aqui, pois Heroku usa Postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default # Herda as configurações do "default"
  adapter: sqlite3 # Para desenvolvimento local, SQLite ainda é ok
  database: storage/development.sqlite3

test:
  <<: *default # Herda as configurações do "default"
  adapter: sqlite3 # Para teste local, SQLite ainda é ok
  database: storage/test.sqlite3

production:
  <<: *default # Herda as configurações do "default"
  url: <%= ENV['DATABASE_URL'] %> # O Heroku fornece esta URL para o PostgreSQL
  # sslmode: require # Descomente se tiver problemas de conexão SSL no Heroku, mas geralmente não é necessário com o DATABASE_URL padrão.

cable:
  <<: *default # Também herda do "default"
  url: <%= ENV['DATABASE_URL'] %> # Aponta para o mesmo banco de dados do Heroku

queue:
  <<: *default # Também herda do "default"
  url: <%= ENV['DATABASE_URL'] %> # Aponta para o mesmo banco de dados do Heroku

cache:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>